// gen_wasm_progs_main.go — build-time generator for the wasm progs embed.
// Run from the repo root via `go run ./cmd/ironwailgo/gen_wasm_progs` (wired
// into mise build-wasm) after `mise run build-progs` has produced
// pkg/qgo/quakego/progs.dat. Writes cmd/ironwailgo/progs_data.go with the
// embedded bytes so the wasm binary needs no `go` binary or disk at runtime.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func main() {
	// Resolve repo root from the working directory (repo root when run via
	// mise; also fine from cmd/ironwailgo).
	root, err := filepath.Abs(".")
	if err != nil {
		fatal("abs: %v", err)
	}
	for {
		if _, err := os.Stat(filepath.Join(root, "go.mod")); err == nil {
			break
		}
		parent := filepath.Dir(root)
		if parent == root {
			fatal("repo root (go.mod) not found above %s", root)
		}
		root = parent
	}

	src := filepath.Join(root, "pkg", "qgo", "quakego", "progs.dat")
	data, err := os.ReadFile(src)
	if err != nil {
		fatal("read %s: %v (run `mise run build-progs` first)", src, err)
	}

	out := filepath.Join(root, "cmd", "ironwailgo", "progs_data.go")
	l := strings.Builder{}
	l.WriteString("// Code generated by gen_wasm_progs; DO NOT EDIT.\n")
	l.WriteString("//go:build js && wasm\n\n")
	l.WriteString("package main\n\n")
	l.WriteString("// embeddedProgsData is the precompiled QuakeGo progs.dat, embedded\n")
	l.WriteString("// so the no-assets wasm boot needs no `go` binary or disk at runtime.\n")
	l.WriteString("var embeddedProgsData = []byte{\n")
	// Emit each byte as `0x%02x,` (trailing comma required before the closing
	// brace in a multi-line composite literal), 16 bytes per line.
	for i, b := range data {
		if i%16 == 0 {
			l.WriteString("\t")
		}
		fmt.Fprintf(&l, "0x%02x, ", b)
		if i%16 == 15 {
			l.WriteString("\n")
		}
	}
	if len(data)%16 != 0 {
		l.WriteString("\n")
	}
	l.WriteString("}\n")

	if err := os.WriteFile(out, []byte(l.String()), 0o644); err != nil {
		fatal("write %s: %v", out, err)
	}
	fmt.Printf("wrote %s (%d bytes -> %s)\n", out, len(data), filepath.Join("cmd", "ironwailgo", "progs_data.go"))
}

func fatal(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "gen_wasm_progs: "+format+"\n", args...)
	os.Exit(1)
}
