// Code generated by "stringer --type LumpType"; DO NOT EDIT.

package image

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypNone-0]
	_ = x[TypLabel-1]
	_ = x[TypLumpy-64]
	_ = x[TypPalette-64]
	_ = x[TypQTex-65]
	_ = x[TypQPic-66]
	_ = x[TypSound-67]
	_ = x[TypMipTex-68]
	_ = x[TypConsolePic-69]
}

const (
	_LumpType_name_0 = "TypNoneTypLabel"
	_LumpType_name_1 = "TypLumpyTypQTexTypQPicTypSoundTypMipTexTypConsolePic"
)

var (
	_LumpType_index_0 = [...]uint8{0, 7, 15}
	_LumpType_index_1 = [...]uint8{0, 8, 15, 22, 30, 39, 52}
)

func (i LumpType) String() string {
	switch {
	case 0 <= i && i <= 1:
		return _LumpType_name_0[_LumpType_index_0[i]:_LumpType_index_0[i+1]]
	case 64 <= i && i <= 69:
		i -= 64
		return _LumpType_name_1[_LumpType_index_1[i]:_LumpType_index_1[i+1]]
	default:
		return "LumpType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
