// Code generated by "stringer -type=EntityFlags"; DO NOT EDIT.

package quake

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FlagFly-1]
	_ = x[FlagSwim-2]
	_ = x[FlagClient-8]
	_ = x[FlagInWater-16]
	_ = x[FlagMonster-32]
	_ = x[FlagGodMode-64]
	_ = x[FlagNoTarget-128]
	_ = x[FlagItem-256]
	_ = x[FlagOnGround-512]
	_ = x[FlagPartialGround-1024]
	_ = x[FlagWaterJump-2048]
	_ = x[FlagJumpReleased-4096]
	_ = x[FlagIsBot-8192]
	_ = x[FlagNoPlayers-16384]
	_ = x[FlagNoMonsters-32768]
	_ = x[FlagNoBots-65536]
	_ = x[FlagObjective-131072]
}

const _EntityFlags_name = "FlagFlyFlagSwimFlagClientFlagInWaterFlagMonsterFlagGodModeFlagNoTargetFlagItemFlagOnGroundFlagPartialGroundFlagWaterJumpFlagJumpReleasedFlagIsBotFlagNoPlayersFlagNoMonstersFlagNoBotsFlagObjective"

var _EntityFlags_map = map[EntityFlags]string{
	1:      _EntityFlags_name[0:7],
	2:      _EntityFlags_name[7:15],
	8:      _EntityFlags_name[15:25],
	16:     _EntityFlags_name[25:36],
	32:     _EntityFlags_name[36:47],
	64:     _EntityFlags_name[47:58],
	128:    _EntityFlags_name[58:70],
	256:    _EntityFlags_name[70:78],
	512:    _EntityFlags_name[78:90],
	1024:   _EntityFlags_name[90:107],
	2048:   _EntityFlags_name[107:120],
	4096:   _EntityFlags_name[120:136],
	8192:   _EntityFlags_name[136:145],
	16384:  _EntityFlags_name[145:158],
	32768:  _EntityFlags_name[158:172],
	65536:  _EntityFlags_name[172:182],
	131072: _EntityFlags_name[182:195],
}

func (i EntityFlags) String() string {
	if str, ok := _EntityFlags_map[i]; ok {
		return str
	}
	return "EntityFlags(" + strconv.FormatInt(int64(i), 10) + ")"
}
