package compiler

import (
	"go/ast"
	"go/parser"
	"go/token"
	"go/types"
	"os"
	"path/filepath"
	"strings"

	"github.com/ironwail/ironwail-go/internal/qc"
	"golang.org/x/tools/go/packages"
)

// Compiler orchestrates the full Go → progs.dat compilation pipeline.
type Compiler struct {
	Verbose bool
}

// New creates a new Compiler instance.
func New() *Compiler {
	return &Compiler{}
}

// Compile compiles a Go package directory into a progs.dat binary.
func (c *Compiler) Compile(dir string) ([]byte, error) {
	// Discover all .go and .qgo files in the directory to build an overlay
	// for packages.Load (which doesn't natively support .qgo).
	overlay := make(map[string][]byte)
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}

	hasGo := false
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		name := entry.Name()
		if strings.HasSuffix(name, ".go") {
			hasGo = true
		}
		if strings.HasSuffix(name, ".qgo") {
			path := filepath.Join(dir, name)
			content, err := os.ReadFile(path)
			if err != nil {
				return nil, err
			}
			// Map .qgo files to .go filenames in the same directory for the overlay.
			overlay[path[:len(path)-4]+".go"] = content
			hasGo = true
		}
	}

	if !hasGo {
		return nil, &CompileError{Msg: "no Go or .qgo files found in " + dir}
	}

	// Ensure go/packages sees this as a package by having at least one real .go file on disk.
	// We check if there are ANY .go files on disk.
	hasRealGo := false
	for _, entry := range entries {
		if !entry.IsDir() && strings.HasSuffix(entry.Name(), ".go") {
			hasRealGo = true
			break
		}
	}

	// Ensure we use the correct package name for any injected file
	pkgName := "main"
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		ext := filepath.Ext(entry.Name())
		if ext == ".go" || ext == ".qgo" {
			f, err := parser.ParseFile(token.NewFileSet(), filepath.Join(dir, entry.Name()), nil, parser.PackageClauseOnly)
			if err == nil {
				pkgName = f.Name.Name
				break
			}
		}
	}

	if !hasRealGo {
		dummyFile := filepath.Join(dir, "qgo_autogen_dummy.go")
		if err := os.WriteFile(dummyFile, []byte("// Autogenerated by qgo\npackage "+pkgName+"\n"), 0644); err != nil {
			return nil, err
		}
		defer os.Remove(dummyFile)
	}

	cfg := &packages.Config{
		Mode:    packages.NeedName | packages.NeedFiles | packages.NeedCompiledGoFiles | packages.NeedImports | packages.NeedDeps | packages.NeedTypes | packages.NeedSyntax | packages.NeedTypesInfo | packages.NeedModule,
		Dir:     dir,
		Overlay: overlay,
		ParseFile: func(fset *token.FileSet, filename string, src []byte) (*ast.File, error) {
			// Ensure we parse comments
			return parser.ParseFile(fset, filename, src, parser.ParseComments)
		},
	}

	cfg.Env = os.Environ()

	pkgs, err := packages.Load(cfg, ".")
	if err != nil {
		return nil, err
	}

	if packages.PrintErrors(pkgs) > 0 {
		return nil, &CompileError{Msg: "errors during package loading"}
	}

	if len(pkgs) == 0 {
		return nil, &CompileError{Msg: "no packages found in " + dir}
	}

	// Lower AST → IR
	lowerer := NewLowerer()
	irProg, err := lowerer.LowerPackages(pkgs)
	if err != nil {
		return nil, err
	}

	// Code generation: IR → QCVM
	globals := NewGlobalAllocator()
	strings := NewStringTable()
	codegen := NewCodeGen(globals, strings)

	emitInput, err := codegen.Generate(irProg)
	if err != nil {
		return nil, err
	}

	// Emit binary
	return Emit(emitInput)
}

func goBasicTypeToQC(t types.Type) qc.EType {
	if named, ok := t.(*types.Named); ok {
		switch named.Obj().Name() {
		case "Vec3":
			return EvVector
		case "Entity":
			return EvEntity
		case "Func":
			return EvFunction
		case "FieldOffset":
			return EvField
		}
		return goBasicTypeToQC(named.Underlying())
	}
	switch bt := t.Underlying().(type) {
	case *types.Basic:
		switch bt.Kind() {
		case types.Float32, types.Float64, types.UntypedFloat,
			types.Int, types.Int32, types.Int64, types.UntypedInt,
			types.Bool, types.UntypedBool:
			return EvFloat
		case types.String, types.UntypedString:
			return EvString
		case types.Uintptr:
			return EvEntity
		}
	case *types.Array:
		if bt.Len() == 3 {
			return EvVector
		}
	case *types.Signature:
		return EvFunction
	}
	return EvFloat
}
