package transpile

import (
	"fmt"
	"strings"
)

// Emit renders parsed QuakeC declarations as QuakeGo source.
//
// The output targets the conventions of pkg/qgo/quakego: QC entity refs
// (self/other/activator/world) become the exported engine globals, entity
// fields use the Entity struct's exported names, engine builtins are
// engine.X calls, and constants keep their QC spelling.
//
// The transpiler is a starting point, not a hand-port replacement: constructs
// it cannot safely convert (function-pointer field reassignments, QC
// extensions) are emitted as TODO comments rather than guessed at.
type Emitter struct {
	// Package is the Go package clause written at the top of the output.
	Package string

	sb      strings.Builder
	indent  int
	unknown []string // constructs reported via TODO comments

	// locals tracks names declared as function locals or params in the
	// function currently being emitted. Idents matching a local render with
	// their QC name instead of the engine-global mapping.
	locals map[string]bool
}

// Output returns the rendered source.
func (e *Emitter) Output() string { return e.sb.String() }

// Unknowns lists the constructs the emitter had to skip, for the CLI to
// surface (count + first occurrence each).
func (e *Emitter) Unknowns() []string { return e.unknown }

// EmitProgram renders a whole file: package clause, then every declaration.
func (e *Emitter) EmitProgram(decls []Decl) {
	pkg := e.Package
	if pkg == "" {
		pkg = "progs"
	}
	fmt.Fprintf(&e.sb, "// Code generated by qcmod qc2go from QuakeC source; refine by hand.\n")
	fmt.Fprintf(&e.sb, "package %s\n\n", pkg)
	fmt.Fprintf(&e.sb, "import (\n\t\"quake\"\n\t\"quake/engine\"\n)\n\n")

	for _, d := range decls {
		switch x := d.(type) {
		case *FieldDecl:
			e.emitFieldDecl(x)
		case *GlobalDecl:
			e.emitGlobalDecl(x)
		case *FuncDecl:
			e.emitFuncDecl(x)
		}
	}
}

// emitFieldDecl comments the declaration: standard entity fields already
// exist on the Entity struct; mod-specific ones need EngineRegister calls.
func (e *Emitter) emitFieldDecl(d *FieldDecl) {
	if _, known := entityFields[d.Name]; known {
		fmt.Fprintf(&e.sb, "// field .%s %s — already defined on quake.Entity\n", d.QCType, d.Name)
		return
	}
	fmt.Fprintf(&e.sb, "// TODO(transpile): register custom entity field .%s %s via the engine's field registry\n", d.QCType, d.Name)
}

// emitGlobalDecl renders a global as an exported package var. Initialisers
// are re-rendered from the parsed expression where the emitter knows how.
func (e *Emitter) emitGlobalDecl(d *GlobalDecl) {
	goType := goTypeName(d.QCType)
	if d.Value == "" {
		fmt.Fprintf(&e.sb, "var %s %s\n\n", goName(d.Name), goType)
		return
	}
	// Re-parse the captured initialiser text so constants/identifiers map.
	if sub, err := Parse(fmt.Sprintf("%s __init__ = %s;\n", d.QCType, d.Value)); err == nil && len(sub) == 1 {
		if g, ok := sub[0].(*GlobalDecl); ok && g.Value != "" {
			if init, err := e.parseInitExpr(d.QCType, g.Value); err == nil {
				fmt.Fprintf(&e.sb, "var %s %s = %s\n\n", goName(d.Name), goType, init)
				return
			}
		}
	}
	fmt.Fprintf(&e.sb, "var %s %s // TODO(transpile): initialiser %s\n\n", goName(d.Name), goType, d.Value)
}

// emitFuncDecl renders a function with its mapped body.
func (e *Emitter) emitFuncDecl(d *FuncDecl) {
	sig := goFuncSignature(d)
	if d.Alias != "" {
		fmt.Fprintf(&e.sb, "// %s is an alias for %s\n", goName(d.Name), d.Alias)
		fmt.Fprintf(&e.sb, "var %s = %s\n\n", goName(d.Name), d.Alias)
		return
	}

	fmt.Fprintf(&e.sb, "func %s {\n", sig)
	e.locals = make(map[string]bool)
	for _, p := range d.Params {
		e.locals[p.Name] = true
	}
	e.indent++
	for _, st := range d.Body {
		e.emitStmt(st)
	}
	e.indent--
	fmt.Fprintf(&e.sb, "}\n\n")
}

// goFuncSignature renders the Go function signature for a QC function,
// including named parameters (QC parameters are engine globals; the QuakeGo
// port mirrors them as ordinary Go params so the body reads naturally).
func goFuncSignature(d *FuncDecl) string {
	var params []string
	for _, p := range d.Params {
		params = append(params, fmt.Sprintf("%s %s", p.Name, goTypeName(p.QCType)))
	}
	sig := qcFuncName(d.Name) + "(" + strings.Join(params, ", ") + ")"
	if ret := goTypeName(d.QCType); ret != "" {
		sig += " " + ret
	}
	return sig
}

// emitStmt renders one statement at the current indentation.
func (e *Emitter) emitStmt(st Stmt) {
	pad := strings.Repeat("\t", e.indent)
	switch x := st.(type) {
	case *ExprStmt:
		fmt.Fprintf(&e.sb, "%s%s\n", pad, e.expr(x.X))

	case *AssignStmt:
		fmt.Fprintf(&e.sb, "%s%s = %s\n", pad, e.expr(x.LHS), e.expr(x.RHS))

	case *IfStmt:
		fmt.Fprintf(&e.sb, "%sif %s {\n", pad, e.condExpr(x.Cond))
		e.indent++
		e.emitStmt(x.Then)
		e.indent--
		if x.Else != nil {
			fmt.Fprintf(&e.sb, "%s} else {\n", pad)
			e.indent++
			e.emitStmt(x.Else)
			e.indent--
		}
		fmt.Fprintf(&e.sb, "%s}\n", pad)

	case *WhileStmt:
		fmt.Fprintf(&e.sb, "%sfor %s {\n", pad, e.condExpr(x.Cond))
		e.indent++
		e.emitStmt(x.Body)
		e.indent--
		fmt.Fprintf(&e.sb, "%s}\n", pad)

	case *DoWhileStmt:
		fmt.Fprintf(&e.sb, "%sfor {\n", pad)
		e.indent++
		e.emitStmt(x.Body)
		fmt.Fprintf(&e.sb, "%sif !(%s) {\n\tbreak\n}\n", pad, e.condExpr(x.Cond))
		e.indent--
		fmt.Fprintf(&e.sb, "%s}\n", pad)

	case *ForStmt:
		init, cond, post := "", "", ""
		if x.Init != nil {
			init = e.stmtInline(x.Init)
		}
		if x.Cond != nil {
			cond = e.condExpr(x.Cond)
		}
		if x.Post != nil {
			post = e.stmtInline(x.Post)
		}
		fmt.Fprintf(&e.sb, "%sfor %s; %s; %s {\n", pad, init, cond, post)
		e.indent++
		e.emitStmt(x.Body)
		e.indent--
		fmt.Fprintf(&e.sb, "%s}\n", pad)

	case *ReturnStmt:
		if x.Value != nil {
			fmt.Fprintf(&e.sb, "%sreturn %s\n", pad, e.expr(x.Value))
		} else {
			fmt.Fprintf(&e.sb, "%sreturn\n", pad)
		}

	case *BlockStmt:
		for _, inner := range x.List {
			e.emitStmt(inner)
		}

	case *LocalList:
		for _, d := range x.Decls {
			e.emitStmt(d)
		}

	case *LocalDecl:
		if e.locals == nil {
			e.locals = make(map[string]bool)
		}
		e.locals[x.Name] = true
		if x.Init != "" {
			fmt.Fprintf(&e.sb, "%s%s := %s\n", pad, x.Name, e.initExpr(x.QCType, x.Init))
		} else {
			fmt.Fprintf(&e.sb, "%svar %s %s\n", pad, x.Name, goTypeName(x.QCType))
		}

	default:
		fmt.Fprintf(&e.sb, "%s// TODO(transpile): unsupported statement %T\n", pad, st)
	}
}

// stmtInline renders a statement without a trailing newline (for for-loop
// init/post slots).
func (e *Emitter) stmtInline(st Stmt) string {
	switch x := st.(type) {
	case *AssignStmt:
		return fmt.Sprintf("%s = %s", e.expr(x.LHS), e.expr(x.RHS))
	case *ExprStmt:
		return e.expr(x.X)
	case *LocalDecl:
		if x.Init != "" {
			return fmt.Sprintf("%s := %s", x.Name, e.initExpr(x.QCType, x.Init))
		}
		return fmt.Sprintf("var %s %s", x.Name, goTypeName(x.QCType))
	}
	return ""
}

// condExpr renders an expression in boolean position, applying QC truthiness:
// floats/entities compared against zero, strings against StringNull, and
// classic QC `&` between flag operands as an int bitwise test.
func (e *Emitter) condExpr(x Expr) string {
	if b, ok := x.(*Binary); ok && isComparison(b.Op) {
		return fmt.Sprintf("%s %s %s", e.expr(b.LHS), b.Op, e.expr(b.RHS))
	}
	if b, ok := x.(*Binary); ok && b.Op == "&" {
		return fmt.Sprintf("(int(%s) & int(%s)) != 0", e.expr(b.LHS), e.expr(b.RHS))
	}
	if b, ok := x.(*Binary); ok && (b.Op == "&&" || b.Op == "||") {
		return fmt.Sprintf("%s %s %s", e.condExpr(b.LHS), b.Op, e.condExpr(b.RHS))
	}
	return e.truthy(x)
}

// truthy renders `expr` under QC truthiness (non-zero / non-null).
func (e *Emitter) truthy(x Expr) string {
	if u, ok := x.(*Unary); ok && u.Op == "!" {
		inner := e.expr(u.Operand)
		// `!x` inverts truthiness: floats become == 0, strings == StringNull.
		if f, ok := u.Operand.(*FieldAccess); ok && isStringField(f.Field) {
			return fmt.Sprintf("%s == StringNull", inner)
		}
		if isStringCall(u.Operand) {
			return fmt.Sprintf("%s == StringNull", inner)
		}
		return fmt.Sprintf("%s == 0", inner)
	}
	if f, ok := x.(*FieldAccess); ok && isStringField(f.Field) {
		return fmt.Sprintf("%s != StringNull", e.expr(f))
	}
	if c, ok := x.(*Call); ok && isStringCall(c) {
		return fmt.Sprintf("%s != StringNull", e.expr(c))
	}
	return fmt.Sprintf("%s != 0", e.expr(x))
}

// isComparison reports whether op is a QC comparison operator.
func isComparison(op string) bool {
	switch op {
	case "==", "!=", "<", ">", "<=", ">=":
		return true
	}
	return false
}

// isStringField reports whether a QC entity field holds a string (per the
// generated Entity field table's type). The table maps names only, so this
// checks the known string fields seen in the QuakeGo port.
func isStringField(qcName string) bool {
	switch qcName {
	case "classname", "model", "target", "targetname", "message", "noise",
		"noise1", "noise2", "noise3", "netname", "map":
		return true
	}
	return false
}

// isStringCall reports whether a call returns a string (engine builtins only;
// QC float() user functions do not qualify).
func isStringCall(x Expr) bool {
	c, ok := x.(*Call)
	if !ok {
		return false
	}
	switch strings.ToLower(c.Name) {
	case "ftos", "vtos", "etos", "precache_sound", "precache_model":
		return true
	}
	return false
}

// expr renders an expression in QuakeGo form.
func (e *Emitter) expr(x Expr) string {
	switch v := x.(type) {
	case *Ident:
		if e.locals != nil && e.locals[v.Name] {
			return v.Name
		}
		return goName(v.Name)
	case *FieldAccess:
		return goName(v.Recv) + "." + fieldName(v.Field)
	case *StringLit:
		return fmt.Sprintf("%q", v.Value)
	case *NumberLit:
		return v.Text
	case *VectorLit:
		return fmt.Sprintf("quake.MakeVec3(%s, %s, %s)", v.X, v.Y, v.Z)
	case *Call:
		args := make([]string, len(v.Args))
		for i, a := range v.Args {
			args[i] = e.expr(a)
		}
		return builtinCall(v.Name, args)
	case *Unary:
		if v.Op == "!" {
			return "!(" + e.condExpr(v.Operand) + ")"
		}
		return v.Op + e.expr(v.Operand)
	case *Binary:
		switch v.Op {
		case "&":
			return fmt.Sprintf("int(%s) & int(%s)", e.expr(v.LHS), e.expr(v.RHS))
		default:
			return fmt.Sprintf("%s %s %s", e.expr(v.LHS), v.Op, e.expr(v.RHS))
		}
	case *Ternary:
		return fmt.Sprintf("ternary(%s, func() any { return %s }, func() any { return %s })",
			e.condExpr(v.Cond), e.expr(v.Then), e.expr(v.Else))
	}
	return "<expr>"
}

// initExpr renders a raw initialiser captured as text for the given QC type.
func (e *Emitter) initExpr(qcType, raw string) string {
	toks, err := Lex(raw)
	if err != nil {
		return raw
	}
	p := &parser{toks: toks}
	x, err := p.parseExpr()
	if err != nil {
		return raw
	}
	_ = x
	// Re-lex through the emitter by parsing the captured text into an expr.
	sub, err := Parse(fmt.Sprintf("float __x = %s;", raw))
	if err != nil || len(sub) != 1 {
		return raw
	}
	g, ok := sub[0].(*GlobalDecl)
	if !ok || g.Value == "" {
		return raw
	}
	reparsed, err := Lex(g.Value)
	if err != nil || len(reparsed) == 0 {
		return raw
	}
	pp := &parser{toks: reparsed}
	ex, err := pp.parseExpr()
	if err != nil {
		return raw
	}
	return e.expr(ex)
}

// parseInitExpr parses a raw initialiser captured at top level into Go form.
// Used by global declarations; the double-parse keeps the capture simple.
func (e *Emitter) parseInitExpr(qcType, raw string) (string, error) {
	sub, err := Parse(fmt.Sprintf("%s __init__ = %s;", qcType, raw))
	if err != nil || len(sub) != 1 {
		return "", fmt.Errorf("reparse failed")
	}
	g, ok := sub[0].(*GlobalDecl)
	if !ok || g.Value == "" {
		return "", fmt.Errorf("no initialiser")
	}
	toks, err := Lex(g.Value)
	if err != nil {
		return "", err
	}
	p := &parser{toks: toks}
	x, err := p.parseExpr()
	if err != nil {
		return "", err
	}
	return e.expr(x), nil
}
