package transpile

// engineBuiltins maps a QC builtin call name (lowercased) to the Go function
// on the quake/engine package that implements it. Generated from
// pkg/qgo/quake/engine/builtins.go; QC builtins implemented in the qc layer
// or requiring special call forms are handled before this table is consulted.
//
// Calls whose lowercased name is absent from this table are user functions —
// they keep their QC name and stay unprefixed.
var engineBuiltins = map[string]string{
	"makevectors":        "MakeVectors",
	"setorigin":          "SetOrigin",
	"setmodel":           "SetModel",
	"setsize":            "SetSize",
	"breakstatement":     "BreakStatement",
	"random":             "Random",
	"sound":              "Sound",
	"normalize":          "Normalize",
	"error":              "Error",
	"objerror":           "ObjError",
	"vlen":               "Vlen",
	"vectoyaw":           "Vectoyaw",
	"spawn":              "Spawn",
	"remove":             "Remove",
	"traceline":          "Traceline",
	"checkclient":        "CheckClient",
	"find":               "Find",
	"precachesound":      "PrecacheSound",
	"precachemodel":      "PrecacheModel",
	"stuffcmd":           "StuffCmd",
	"findradius":         "FindRadius",
	"bprint":             "Bprint",
	"sprint":             "SPrint",
	"print":              "Print",
	"dprint":             "Dprint",
	"ftos":               "Ftos",
	"vtos":               "Vtos",
	"eprint":             "EPrint",
	"walkmove":           "WalkMove",
	"droptofloor":        "DropToFloor",
	"lightstyle":         "LightStyle",
	"rint":               "RInt",
	"floor":              "Floor",
	"ceil":               "Ceil",
	"checkbottom":        "CheckBottom",
	"pointcontents":      "PointContents",
	"fabs":               "FAbs",
	"aim":                "Aim",
	"cvar":               "Cvar",
	"localcmd":           "LocalCmd",
	"getnextent":         "GetNextEnt",
	"particle":           "Particle",
	"changeyaw":          "ChangeYaw",
	"vectoangles":        "VectoAngles",
	"writebyte":          "WriteByte",
	"writechar":          "WriteChar",
	"writeshort":         "WriteShort",
	"writelong":          "WriteLong",
	"writecoord":         "WriteCoord",
	"writeangle":         "WriteAngle",
	"writestring":        "WriteString",
	"writeentity":        "WriteEntity",
	"sin":                "Sin",
	"cos":                "Cos",
	"sqrt":               "Sqrt",
	"etos":               "Etos",
	"movetogoal":         "MoveToGoal",
	"precachefile":       "PrecacheFile",
	"makestatic":         "MakeStatic",
	"changelevel":        "Changelevel",
	"cvarset":            "CvarSet",
	"centerprint":        "Centerprint",
	"ambientsound":       "Ambientsound",
	"precachemodel2":     "PrecacheModel2",
	"precachesound2":     "PrecacheSound2",
	"precachefile2":      "PrecacheFile2",
	"setspawnparms":      "SetSpawnParms",
	"finalefinished":     "FinaleFinished",
	"localsound":         "LocalSound",
	"stof":               "Stof",
	"min":                "Min",
	"max":                "Max",
	"bound":              "Bound",
	"pow":                "Pow",
	"checkextension":     "CheckExtension",
	"checkplayerexflags": "CheckPlayerEXFlags",
	"strlen":             "Strlen",
	"strcat":             "Strcat",
	"substring":          "Substring",
	"stov":               "Stov",
	"strzone":            "Strzone",
	"strunzone":          "Strunzone",
	"str2chr":            "Str2chr",
	"chr2str":            "Chr2str",
	"mod":                "Mod",
	"asin":               "Asin",
	"acos":               "Acos",
	"atan":               "Atan",
	"atan2":              "Atan2",
	"tan":                "Tan",
}
